### ISSUE TITLE
sample?

### ISSUE THREAD

**Issue by haowenjiang** [nextbreakpoint/ffmpeg4java#1]
sample?

Exception in thread "main" java.lang.UnsatisfiedLinkError: no ffmpeg4java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at com.nextbreakpoint.ffmpeg4java.FFmpeg4Java.<clinit>(FFmpeg4Java.java:23)

**Comment by nextbreakpoint** [comment]
Could you explain how did you get this error? Did you try to run the test example? Which operating system?

**Comment by nextbreakpoint** [comment]
Please reopen the issue providing more information
